import { LineType, Language } from "./types";

export const MAX_LINES = 6;

export const COIN_VALUES = {
  BACK: 2,
  FRONT: 3,
};

export const TRIGRAMS: Record<number, Record<Language, { name: string, element: string, nature: string, attribute: string }>> = {
  0: { // Earth (Kun)
     'zh-CN': { name: '坤', element: '土', nature: '地', attribute: '顺' },
     'zh-TW': { name: '坤', element: '土', nature: '地', attribute: '順' },
     'en': { name: 'Kun', element: 'Earth', nature: 'Earth', attribute: 'Receptive' },
     'ja': { name: '坤', element: '土', nature: '地', attribute: '従順' }
  },
  1: { // Thunder (Zhen)
     'zh-CN': { name: '震', element: '木', nature: '雷', attribute: '动' },
     'zh-TW': { name: '震', element: '木', nature: '雷', attribute: '動' },
     'en': { name: 'Zhen', element: 'Wood', nature: 'Thunder', attribute: 'Arousing' },
     'ja': { name: '震', element: '木', nature: '雷', attribute: '動' }
  },
  2: { // Water (Kan)
     'zh-CN': { name: '坎', element: '水', nature: '水', attribute: '陷' },
     'zh-TW': { name: '坎', element: '水', nature: '水', attribute: '陷' },
     'en': { name: 'Kan', element: 'Water', nature: 'Water', attribute: 'Abysmal' },
     'ja': { name: '坎', element: '水', nature: '水', attribute: '陥る' }
  },
  3: { // Lake (Dui)
     'zh-CN': { name: '兑', element: '金', nature: '泽', attribute: '悦' },
     'zh-TW': { name: '兌', element: '金', nature: '澤', attribute: '悅' },
     'en': { name: 'Dui', element: 'Metal', nature: 'Lake', attribute: 'Joyous' },
     'ja': { name: '兌', element: '金', nature: '沢', attribute: '喜び' }
  },
  4: { // Mountain (Gen)
     'zh-CN': { name: '艮', element: '土', nature: '山', attribute: '止' },
     'zh-TW': { name: '艮', element: '土', nature: '山', attribute: '止' },
     'en': { name: 'Gen', element: 'Earth', nature: 'Mountain', attribute: 'Stillness' },
     'ja': { name: '艮', element: '土', nature: '山', attribute: '停止' }
  },
  5: { // Fire (Li)
     'zh-CN': { name: '离', element: '火', nature: '火', attribute: '丽' },
     'zh-TW': { name: '離', element: '火', nature: '火', attribute: '麗' },
     'en': { name: 'Li', element: 'Fire', nature: 'Fire', attribute: 'Clinging' },
     'ja': { name: '離', element: '火', nature: '火', attribute: '付く' }
  },
  6: { // Wind (Xun)
     'zh-CN': { name: '巽', element: '木', nature: '风', attribute: '入' },
     'zh-TW': { name: '巽', element: '木', nature: '風', attribute: '入' },
     'en': { name: 'Xun', element: 'Wood', nature: 'Wind', attribute: 'Gentle' },
     'ja': { name: '巽', element: '木', nature: '風', attribute: '入り込む' }
  },
  7: { // Heaven (Qian)
     'zh-CN': { name: '乾', element: '金', nature: '天', attribute: '健' },
     'zh-TW': { name: '乾', element: '金', nature: '天', attribute: '健' },
     'en': { name: 'Qian', element: 'Metal', nature: 'Heaven', attribute: 'Creative' },
     'ja': { name: '乾', element: '金', nature: '天', attribute: '剛健' }
  }
};

// Hexagram Names mapped by ID: (UpperTrigram << 3) | LowerTrigram
export const HEXAGRAM_NAMES: Record<number, Record<Language, string>> = {
  0: { 'zh-CN': '坤为地', 'zh-TW': '坤為地', 'en': 'Kun (The Receptive)', 'ja': '坤為地' },
  1: { 'zh-CN': '地雷复', 'zh-TW': '地雷復', 'en': 'Fu (Return)', 'ja': '地雷復' },
  2: { 'zh-CN': '地水师', 'zh-TW': '地水師', 'en': 'Shi (The Army)', 'ja': '地水師' },
  3: { 'zh-CN': '地泽临', 'zh-TW': '地澤臨', 'en': 'Lin (Approach)', 'ja': '地澤臨' },
  4: { 'zh-CN': '地山谦', 'zh-TW': '地山謙', 'en': 'Qian (Humility)', 'ja': '地山謙' },
  5: { 'zh-CN': '地火明夷', 'zh-TW': '地火明夷', 'en': 'Ming Yi (Darkening of the Light)', 'ja': '地火明夷' },
  6: { 'zh-CN': '地风升', 'zh-TW': '地風升', 'en': 'Sheng (Pushing Upward)', 'ja': '地風升' },
  7: { 'zh-CN': '地天泰', 'zh-TW': '地天泰', 'en': 'Tai (Peace)', 'ja': '地天泰' },
  8: { 'zh-CN': '雷地豫', 'zh-TW': '雷地豫', 'en': 'Yu (Enthusiasm)', 'ja': '雷地豫' },
  9: { 'zh-CN': '震为雷', 'zh-TW': '震為雷', 'en': 'Zhen (The Arousing)', 'ja': '震為雷' },
  10: { 'zh-CN': '雷水解', 'zh-TW': '雷水解', 'en': 'Xie (Deliverance)', 'ja': '雷水解' },
  11: { 'zh-CN': '雷泽归妹', 'zh-TW': '雷澤歸妹', 'en': 'Gui Mei (The Marrying Maiden)', 'ja': '雷澤歸妹' },
  12: { 'zh-CN': '雷山小过', 'zh-TW': '雷山小過', 'en': 'Xiao Guo (Preponderance of the Small)', 'ja': '雷山小過' },
  13: { 'zh-CN': '雷火丰', 'zh-TW': '雷火豐', 'en': 'Feng (Abundance)', 'ja': '雷火豐' },
  14: { 'zh-CN': '雷风恒', 'zh-TW': '雷風恆', 'en': 'Heng (Duration)', 'ja': '雷風恆' },
  15: { 'zh-CN': '雷天大壮', 'zh-TW': '雷天大壯', 'en': 'Da Zhuang (The Power of the Great)', 'ja': '雷天大壯' },
  16: { 'zh-CN': '水地比', 'zh-TW': '水地比', 'en': 'Bi (Holding Together)', 'ja': '水地比' },
  17: { 'zh-CN': '水雷屯', 'zh-TW': '水雷屯', 'en': 'Tun (Difficulty at the Beginning)', 'ja': '水雷屯' },
  18: { 'zh-CN': '坎为水', 'zh-TW': '坎為水', 'en': 'Kan (The Abysmal)', 'ja': '坎為水' },
  19: { 'zh-CN': '水泽节', 'zh-TW': '水澤節', 'en': 'Jie (Limitation)', 'ja': '水澤節' },
  20: { 'zh-CN': '水山蹇', 'zh-TW': '水山蹇', 'en': 'Jian (Obstruction)', 'ja': '水山蹇' },
  21: { 'zh-CN': '水火既济', 'zh-TW': '水火既濟', 'en': 'Ji Ji (After Completion)', 'ja': '水火既濟' },
  22: { 'zh-CN': '水风井', 'zh-TW': '水風井', 'en': 'Jing (The Well)', 'ja': '水風井' },
  23: { 'zh-CN': '水天需', 'zh-TW': '水天需', 'en': 'Xu (Waiting)', 'ja': '水天需' },
  24: { 'zh-CN': '泽地萃', 'zh-TW': '澤地萃', 'en': 'Cui (Gathering Together)', 'ja': '澤地萃' },
  25: { 'zh-CN': '泽雷随', 'zh-TW': '澤雷隨', 'en': 'Sui (Following)', 'ja': '澤雷隨' },
  26: { 'zh-CN': '泽水困', 'zh-TW': '澤水困', 'en': 'Kun (Oppression)', 'ja': '澤水困' },
  27: { 'zh-CN': '兑为泽', 'zh-TW': '兌為澤', 'en': 'Dui (The Joyous)', 'ja': '兌為澤' },
  28: { 'zh-CN': '泽山咸', 'zh-TW': '澤山咸', 'en': 'Xian (Influence)', 'ja': '澤山咸' },
  29: { 'zh-CN': '泽火革', 'zh-TW': '澤火革', 'en': 'Ge (Revolution)', 'ja': '澤火革' },
  30: { 'zh-CN': '泽风大过', 'zh-TW': '澤風大過', 'en': 'Da Guo (Preponderance of the Great)', 'ja': '澤風大過' },
  31: { 'zh-CN': '泽天夬', 'zh-TW': '澤天夬', 'en': 'Guai (Break-through)', 'ja': '澤天夬' },
  32: { 'zh-CN': '山地剥', 'zh-TW': '山地剝', 'en': 'Bo (Splitting Apart)', 'ja': '山地剝' },
  33: { 'zh-CN': '山雷颐', 'zh-TW': '山雷頤', 'en': 'Yi (The Corners of the Mouth)', 'ja': '山雷頤' },
  34: { 'zh-CN': '山水蒙', 'zh-TW': '山水蒙', 'en': 'Meng (Youthful Folly)', 'ja': '山水蒙' },
  35: { 'zh-CN': '山泽损', 'zh-TW': '山澤損', 'en': 'Sun (Decrease)', 'ja': '山澤損' },
  36: { 'zh-CN': '艮为山', 'zh-TW': '艮為山', 'en': 'Gen (Keeping Still)', 'ja': '艮為山' },
  37: { 'zh-CN': '山火贲', 'zh-TW': '山火賁', 'en': 'Bi (Grace)', 'ja': '山火賁' },
  38: { 'zh-CN': '山风蛊', 'zh-TW': '山風蠱', 'en': 'Gu (Work on What Has Been Spoiled)', 'ja': '山風蠱' },
  39: { 'zh-CN': '山天大畜', 'zh-TW': '山天大畜', 'en': 'Da Chu (The Taming of the Power of the Great)', 'ja': '山天大畜' },
  40: { 'zh-CN': '火地晋', 'zh-TW': '火地晉', 'en': 'Jin (Progress)', 'ja': '火地晉' },
  41: { 'zh-CN': '火雷噬嗑', 'zh-TW': '火雷噬嗑', 'en': 'Shi He (Biting Through)', 'ja': '火雷噬嗑' },
  42: { 'zh-CN': '火水未济', 'zh-TW': '火水未濟', 'en': 'Wei Ji (Before Completion)', 'ja': '火水未濟' },
  43: { 'zh-CN': '火泽睽', 'zh-TW': '火澤睽', 'en': 'Kui (Opposition)', 'ja': '火澤睽' },
  44: { 'zh-CN': '火山旅', 'zh-TW': '火山旅', 'en': 'Lu (The Wanderer)', 'ja': '火山旅' },
  45: { 'zh-CN': '离为火', 'zh-TW': '離為火', 'en': 'Li (The Clinging)', 'ja': '離為火' },
  46: { 'zh-CN': '火风鼎', 'zh-TW': '火風鼎', 'en': 'Ding (The Cauldron)', 'ja': '火風鼎' },
  47: { 'zh-CN': '火天大有', 'zh-TW': '火天大有', 'en': 'Da You (Possession in Great Measure)', 'ja': '火天大有' },
  48: { 'zh-CN': '风地观', 'zh-TW': '風地觀', 'en': 'Guan (Contemplation)', 'ja': '風地觀' },
  49: { 'zh-CN': '风雷益', 'zh-TW': '風雷益', 'en': 'Yi (Increase)', 'ja': '風雷益' },
  50: { 'zh-CN': '风水涣', 'zh-TW': '風水渙', 'en': 'Huan (Dispersion)', 'ja': '風水渙' },
  51: { 'zh-CN': '风泽中孚', 'zh-TW': '風澤中孚', 'en': 'Zhong Fu (Inner Truth)', 'ja': '風澤中孚' },
  52: { 'zh-CN': '风山渐', 'zh-TW': '風山漸', 'en': 'Jian (Development)', 'ja': '風山漸' },
  53: { 'zh-CN': '风火家人', 'zh-TW': '風火家人', 'en': 'Jia Ren (The Family)', 'ja': '風火家人' },
  54: { 'zh-CN': '巽为风', 'zh-TW': '巽為風', 'en': 'Xun (The Gentle)', 'ja': '巽為風' },
  55: { 'zh-CN': '风天小畜', 'zh-TW': '風天小畜', 'en': 'Xiao Chu (The Taming of the Power of the Small)', 'ja': '風天小畜' },
  56: { 'zh-CN': '天地否', 'zh-TW': '天地否', 'en': 'Pi (Standstill)', 'ja': '天地否' },
  57: { 'zh-CN': '天雷无妄', 'zh-TW': '天雷無妄', 'en': 'Wu Wang (Innocence)', 'ja': '天雷無妄' },
  58: { 'zh-CN': '天水讼', 'zh-TW': '天水訟', 'en': 'Song (Conflict)', 'ja': '天水訟' },
  59: { 'zh-CN': '天泽履', 'zh-TW': '天澤履', 'en': 'Lu (Treading)', 'ja': '天澤履' },
  60: { 'zh-CN': '天山遁', 'zh-TW': '天山遯', 'en': 'Dun (Retreat)', 'ja': '天山遯' },
  61: { 'zh-CN': '天火同人', 'zh-TW': '天火同人', 'en': 'Tong Ren (Fellowship with Men)', 'ja': '天火同人' },
  62: { 'zh-CN': '天风姤', 'zh-TW': '天風姤', 'en': 'Gou (Coming to Meet)', 'ja': '天風姤' },
  63: { 'zh-CN': '乾为天', 'zh-TW': '乾為天', 'en': 'Qian (The Creative)', 'ja': '乾為天' }
};

export const UI_TEXT: Record<Language, Record<string, string>> = {
  'zh-CN': {
    title: '六爻神算',
    subtitle: '刘伯温秘传 · 赛博算命',
    desc: '诚心默念，摇卦问天。支持离线算法与AI大模型解读。',
    start: '开始起卦',
    tossing: '摇卦中...',
    shake: '摇 卦',
    cast_progress: '第 {current} 爻 / 共 6 爻',
    complete: '卦象已成',
    proceed: '前往解卦',
    question_title: '所问何事？',
    question_label: '你的问题（选填）',
    question_placeholder: '例如：近期事业运势如何？这段感情会有结果吗？',
    interpret: '开始解卦',
    consult_ai: 'AI 深度解读',
    consult_local: '本地速断',
    result_title: '卦象解读',
    new_reading: '重新起卦',
    analyzing: '正在推演天机...',
    mode_ai: 'AI 模型',
    mode_local: '本地算法',
    setting: '设置',
    line_label_bottom: '初爻',
    line_label_2: '二爻',
    line_label_3: '三爻',
    line_label_4: '四爻',
    line_label_5: '五爻',
    line_label_top: '上爻',
    copy_success: '已复制',
    ai_disclaimer: 'AI解读仅供参考，命运掌握在自己手中。',
    switch_lang: '语言',
    switch_mode: '模式',
    // New Sections
    sec_status: '【当前状态】',
    sec_diagnosis: '【六亲诊断】',
    sec_contradiction: '【主要矛盾】',
    sec_future: '【未来趋势】',
    sec_advice: '【行动建议】',
    lbl_subject: '世爻(己)',
    lbl_object: '应爻(彼)',
    lbl_palace: '所属宫位',
    rel_parent: '父母(生我)',
    rel_offspring: '子孙(我生)',
    rel_official: '官鬼(克我)',
    rel_wealth: '妻财(我克)',
    rel_brother: '兄弟(同我)',
    // History
    history_title: '历史记录',
    history_empty: '暂无记录',
    history_clear: '清空记录',
    history_view: '查看详情',
    history_del_confirm: '确定清空所有记录吗？',
    // New Button
    btn_deep_interpret: 'AI 深度详解',
    question_display: '【所问之事】',
  },
  'zh-TW': {
    title: '六爻神算',
    subtitle: '劉伯溫秘傳 · 賽博算命',
    desc: '誠心默念，搖卦問天。支持離線算法與AI大模型解讀。',
    start: '開始起卦',
    tossing: '搖卦中...',
    shake: '搖 卦',
    cast_progress: '第 {current} 爻 / 共 6 爻',
    complete: '卦象已成',
    proceed: '前往解卦',
    question_title: '所問何事？',
    question_label: '你的問題（選填）',
    question_placeholder: '例如：近期事業運勢如何？這段感情會有結果嗎？',
    interpret: '開始解卦',
    consult_ai: 'AI 深度解讀',
    consult_local: '本地速斷',
    result_title: '卦象解讀',
    new_reading: '重新起卦',
    analyzing: '正在推演天機...',
    mode_ai: 'AI 模型',
    mode_local: '本地算法',
    setting: '設置',
    line_label_bottom: '初爻',
    line_label_2: '二爻',
    line_label_3: '三爻',
    line_label_4: '四爻',
    line_label_5: '五爻',
    line_label_top: '上爻',
    copy_success: '已複製',
    ai_disclaimer: 'AI解讀僅供參考，命運掌握在自己手中。',
    switch_lang: '語言',
    switch_mode: '模式',
    sec_status: '【当前状态】',
    sec_diagnosis: '【六親診斷】',
    sec_contradiction: '【主要矛盾】',
    sec_future: '【未來趨勢】',
    sec_advice: '【行動建議】',
    lbl_subject: '世爻(己)',
    lbl_object: '應爻(彼)',
    lbl_palace: '所屬宮位',
    rel_parent: '父母(生我)',
    rel_offspring: '子孫(我生)',
    rel_official: '官鬼(克我)',
    rel_wealth: '妻財(我克)',
    rel_brother: '兄弟(同我)',
    history_title: '歷史記錄',
    history_empty: '暫無記錄',
    history_clear: '清空記錄',
    history_view: '查看詳情',
    history_del_confirm: '確定清空所有記錄嗎？',
    btn_deep_interpret: 'AI 深度詳解',
    question_display: '【所問之事】',
  },
  'en': {
    title: 'Zen Divination',
    subtitle: 'I Ching Hexagram Casting',
    desc: 'Focus your mind, shake the coins, and receive ancient wisdom. Powered by AI & Traditional Logic.',
    start: 'Start Divination',
    tossing: 'Tossing...',
    shake: 'Cast Coins',
    cast_progress: 'Line {current} of 6',
    complete: 'Hexagram Complete',
    proceed: 'Proceed',
    question_title: 'What do you seek?',
    question_label: 'Your Question (Optional)',
    question_placeholder: 'e.g., Should I change jobs? How will my relationship develop?',
    interpret: 'Interpret',
    consult_ai: 'Consult AI',
    consult_local: 'Local Reading',
    result_title: 'Divination Result',
    new_reading: 'New Reading',
    analyzing: 'Consulting the Oracle...',
    mode_ai: 'AI Model',
    mode_local: 'Local Logic',
    setting: 'Settings',
    line_label_bottom: 'Line 1',
    line_label_2: 'Line 2',
    line_label_3: 'Line 3',
    line_label_4: 'Line 4',
    line_label_5: 'Line 5',
    line_label_top: 'Line 6',
    copy_success: 'Copied',
    ai_disclaimer: 'AI interpretations are for guidance only.',
    switch_lang: 'Language',
    switch_mode: 'Mode',
    sec_status: '[ Current Status ]',
    sec_diagnosis: '[ Six Relations Diagnosis ]',
    sec_contradiction: '[ Primary Contradiction ]',
    sec_future: '[ Future Trend ]',
    sec_advice: '[ Action Advice ]',
    lbl_subject: 'Subject (Self)',
    lbl_object: 'Object (Other)',
    lbl_palace: 'Palace',
    rel_parent: 'Parent (Supports You)',
    rel_offspring: 'Offspring (You Support)',
    rel_official: 'Official/Ghost (Controls You)',
    rel_wealth: 'Wealth (You Control)',
    rel_brother: 'Brother (Equals You)',
    history_title: 'History',
    history_empty: 'No records found',
    history_clear: 'Clear History',
    history_view: 'View Details',
    history_del_confirm: 'Are you sure you want to clear all history?',
    btn_deep_interpret: 'Consult AI for Detail',
    question_display: '[ Question ]',
  },
  'ja': {
    title: '六爻神算',
    subtitle: '易経占い',
    desc: '心を静め、硬貨を振って、古の知恵を受け取りましょう。AIと従来のアルゴリズムに対応。',
    start: '占いを始める',
    tossing: '振っています...',
    shake: '硬貨を振る',
    cast_progress: '{current} 爻 / 全 6 爻',
    complete: '卦が完成しました',
    proceed: '解釈へ進む',
    question_title: '何を問いますか？',
    question_label: '質問（任意）',
    question_placeholder: '例：転職すべきか？ この関係はどうなるか？',
    interpret: '占う',
    consult_ai: 'AIで詳しく',
    consult_local: '簡易結果',
    result_title: '占い結果',
    new_reading: '新しく占う',
    analyzing: '天機を推演中...',
    mode_ai: 'AIモデル',
    mode_local: 'ローカル',
    setting: '設定',
    line_label_bottom: '初爻',
    line_label_2: '二爻',
    line_label_3: '三爻',
    line_label_4: '四爻',
    line_label_5: '五爻',
    line_label_top: '上爻',
    copy_success: 'コピーしました',
    ai_disclaimer: 'AIの解釈は参考程度にしてください。',
    switch_lang: '言語',
    switch_mode: 'モード',
    sec_status: '【現状】',
    sec_diagnosis: '【六親診断】',
    sec_contradiction: '【主な矛盾】',
    sec_future: '【未来の傾向】',
    sec_advice: '【行動への助言】',
    lbl_subject: '世爻(自分)',
    lbl_object: '応爻(相手)',
    lbl_palace: '宮',
    rel_parent: '父母(助け)',
    rel_offspring: '子孫(表現)',
    rel_official: '官鬼(圧力)',
    rel_wealth: '妻財(支配)',
    rel_brother: '兄弟(同等)',
    history_title: '履歴',
    history_empty: '記録なし',
    history_clear: '履歴を消去',
    history_view: '詳細を見る',
    history_del_confirm: 'すべての履歴を消去しますか？',
    btn_deep_interpret: 'AIで詳しく分析',
    question_display: '【質問内容】',
  }
};