import { HexagramData, Language, LineType } from "../types";
import { TRIGRAMS, UI_TEXT, HEXAGRAM_NAMES } from "../constants";
import { getHexagramStructure } from "../utils/divination";

// --- Configuration & Dictionaries ---

// 1. Element Interaction Logic
const ELEMENT_RELATIONS: Record<string, Record<string, 'Generate' | 'Overcome' | 'Same' | 'GeneratedBy' | 'OvercomedBy'>> = {
  'Metal': { 'Metal': 'Same', 'Water': 'Generate', 'Wood': 'Overcome', 'Earth': 'GeneratedBy', 'Fire': 'OvercomedBy' },
  'Water': { 'Water': 'Same', 'Wood': 'Generate', 'Fire': 'Overcome', 'Metal': 'GeneratedBy', 'Earth': 'OvercomedBy' },
  'Wood': { 'Wood': 'Same', 'Fire': 'Generate', 'Earth': 'Overcome', 'Water': 'GeneratedBy', 'Metal': 'OvercomedBy' },
  'Fire': { 'Fire': 'Same', 'Earth': 'Generate', 'Metal': 'Overcome', 'Wood': 'GeneratedBy', 'Water': 'OvercomedBy' },
  'Earth': { 'Earth': 'Same', 'Metal': 'Generate', 'Water': 'Overcome', 'Fire': 'GeneratedBy', 'Wood': 'OvercomedBy' },
  // Localized fallbacks
  '金': { '金': 'Same', '水': 'Generate', '木': 'Overcome', '土': 'GeneratedBy', '火': 'OvercomedBy' },
  '水': { '水': 'Same', '木': 'Generate', '火': 'Overcome', '金': 'GeneratedBy', '土': 'OvercomedBy' },
  '木': { '木': 'Same', '火': 'Generate', '土': 'Overcome', '水': 'GeneratedBy', '金': 'OvercomedBy' },
  '火': { '火': 'Same', '土': 'Generate', '金': 'Overcome', '木': 'GeneratedBy', '水': 'OvercomedBy' },
  '土': { '土': 'Same', '金': 'Generate', '水': 'Overcome', '火': 'GeneratedBy', '木': 'OvercomedBy' }
};

// 2. Six Relations Definitions (Principle & Meaning)
const RELATION_DETAILS: Record<string, Record<Language, { meaning: string, principle: string, keywords: string }>> = {
  'Parent': {
    'zh-CN': { meaning: '代表庇护、文书、长辈、操劳。', principle: '生我者为父母（五行相生原理）。', keywords: '辛劳/保护/学习' },
    'zh-TW': { meaning: '代表庇護、文書、長輩、操勞。', principle: '生我者為父母（五行相生原理）。', keywords: '辛勞/保護/學習' },
    'en': { meaning: 'Represents protection, documents, elders, hard work.', principle: 'Generated by the Palace (Element that produces me).', keywords: 'Protection/Docs' },
    'ja': { meaning: '保護、文書、目上の人、苦労を表します。', principle: '自分を生じる五行。', keywords: '保護/苦労' }
  },
  'Offspring': {
    'zh-CN': { meaning: '代表快乐、解忧、投资、才华表达。', principle: '我生者为子孙（五行宣泄原理）。', keywords: '开心/创造/解忧' },
    'zh-TW': { meaning: '代表快樂、解憂、投資、才華表達。', principle: '我生者為子孫（五行宣洩原理）。', keywords: '開心/創造/解憂' },
    'en': { meaning: 'Represents joy, relief, creativity, investment.', principle: 'Generates from the Palace (Element I produce).', keywords: 'Joy/Creativity' },
    'ja': { meaning: '喜び、安心、創造性、投資を表します。', principle: '自分が生じる五行。', keywords: '喜び/表現' }
  },
  'Official': {
    'zh-CN': { meaning: '代表压力、名声、管制、丈夫/男友。', principle: '克我者为官鬼（五行克制原理）。', keywords: '压力/名誉/官方' },
    'zh-TW': { meaning: '代表壓力、名聲、管制、丈夫/男友。', principle: '克我者為官鬼（五行克制原理）。', keywords: '壓力/名譽/官方' },
    'en': { meaning: 'Represents pressure, fame, authority, husband.', principle: 'Overcomes the Palace (Element that controls me).', keywords: 'Pressure/Fame' },
    'ja': { meaning: 'プレッシャー、名声、権威、夫を表します。', principle: '自分を剋する五行。', keywords: '圧力/名声' }
  },
  'Wealth': {
    'zh-CN': { meaning: '代表金钱、控制欲、妻子/女友、下属。', principle: '我克者为妻财（五行掌控原理）。', keywords: '财富/感情/掌控' },
    'zh-TW': { meaning: '代表金錢、控制欲、妻子/女友、下屬。', principle: '我克者為妻財（五行掌控原理）。', keywords: '財富/感情/掌控' },
    'en': { meaning: 'Represents money, control, wife/girlfriend.', principle: 'Overcomed by the Palace (Element I control).', keywords: 'Wealth/Control' },
    'ja': { meaning: '金銭、支配、妻/恋人を表します。', principle: '自分が剋する五行。', keywords: '富/支配' }
  },
  'Brother': {
    'zh-CN': { meaning: '代表竞争、朋友、破财、同辈互助。', principle: '同我者为兄弟（五行比和原理）。', keywords: '竞争/朋友/花费' },
    'zh-TW': { meaning: '代表競爭、朋友、破財、同輩互助。', principle: '同我者為兄弟（五行比和原理）。', keywords: '競爭/朋友/花費' },
    'en': { meaning: 'Represents competition, friends, spending money.', principle: 'Same as the Palace (Element equality).', keywords: 'Competition/Friends' },
    'ja': { meaning: '競争、友人、出費を表します。', principle: '自分と同じ五行。', keywords: '競争/友人' }
  }
};

// 3. Subject (Shi) vs Object (Ying) Detailed Interaction
const INTERACTION_DETAILS: Record<string, Record<Language, { summary: string, detail: string }>> = {
  'Same': {
    'zh-CN': { summary: '比和（和谐/竞争）', detail: '你与所测之事处于平等地位。若是合作则吉利，若是追求独占则有竞争。' },
    'zh-TW': { summary: '比和（和諧/競爭）', detail: '你與所測之事處於平等地位。若是合作則吉利，若是追求獨占則有競爭。' },
    'en': { summary: 'Harmony/Competition', detail: 'You and the objective are equal. Good for partnership, bad for monopoly.' },
    'ja': { summary: '調和/競争', detail: 'あなたと対象は対等です。協力には良いですが、独占には競争があります。' }
  },
  'Generate': {
    'zh-CN': { summary: '我去生彼（付出/投入）', detail: '你主动去追求目标，需要付出精力、金钱或感情。这代表你意愿强烈，但比较辛苦。' },
    'zh-TW': { summary: '我去生彼（付出/投入）', detail: '你主動去追求目標，需要付出精力、金錢或感情。這代表你意願強烈，但比較辛苦。' },
    'en': { summary: 'Investing/Giving', detail: 'You are actively pursuing the goal, requiring effort/money. High willingness but tiring.' },
    'ja': { summary: '投資/努力', detail: 'あなたは目標を積極的に追求しており、努力が必要です。' }
  },
  'GeneratedBy': {
    'zh-CN': { summary: '彼来生我（获益/被爱）', detail: '所测之人或事主动来找你，或者你容易得到外界的帮助。这是最吉利的状态，省力。' },
    'zh-TW': { summary: '彼來生我（獲益/被愛）', detail: '所測之人或事主動來找你，或者你容易得到外界的幫助。這是最吉利的狀態，省力。' },
    'en': { summary: 'Receiving/Benefit', detail: 'The goal comes to you easily. You receive help. Very auspicious and effortless.' },
    'ja': { summary: '恩恵/容易', detail: '目標は向こうからやってきます。助けが得られ、非常に吉です。' }
  },
  'Overcome': {
    'zh-CN': { summary: '我克彼（掌控/征服）', detail: '你处于主导地位，能够控制局势。这利于求财、求职，但需要你有足够的实力去驾驭。' },
    'zh-TW': { summary: '我克彼（掌控/征服）', detail: '你處於主導地位，能夠控制局勢。這利於求財、求職，但需要你有足夠的實力去駕馭。' },
    'en': { summary: 'Controlling/Conquering', detail: 'You are dominant and control the situation. Good for wealth/career, needs strength.' },
    'ja': { summary: '支配/征服', detail: 'あなたは主導権を握っています。富や仕事に良いですが、力が必要です。' }
  },
  'OvercomedBy': {
    'zh-CN': { summary: '彼克我（压力/受制）', detail: '所测之事给你带来压力，或者你受到对方的牵制。局势不由你做主，感到棘手。' },
    'zh-TW': { summary: '彼克我（壓力/受制）', detail: '所測之事給你帶來壓力，或者你受到對方的牽制。局勢不由你做主，感到棘手。' },
    'en': { summary: 'Restricted/Pressured', detail: 'The goal puts pressure on you. You are restricted or controlled by the situation.' },
    'ja': { summary: '圧力/制限', detail: '目標はあなたにプレッシャーを与えます。あなたは状況に支配されています。' }
  }
};

// --- Helpers ---

const getRelKey = (relationName: string, lang: Language): string => {
  const t = UI_TEXT[lang];
  // Simple reverse mapping or keyword check
  if (relationName.includes(t.rel_parent) || relationName.includes('Parent') || relationName.includes('父母')) return 'Parent';
  if (relationName.includes(t.rel_offspring) || relationName.includes('Offspring') || relationName.includes('子孙') || relationName.includes('子孫')) return 'Offspring';
  if (relationName.includes(t.rel_official) || relationName.includes('Official') || relationName.includes('官鬼')) return 'Official';
  if (relationName.includes(t.rel_wealth) || relationName.includes('Wealth') || relationName.includes('妻财') || relationName.includes('妻財')) return 'Wealth';
  if (relationName.includes(t.rel_brother) || relationName.includes('Brother') || relationName.includes('兄弟')) return 'Brother';
  return 'Brother';
};

const getSixRelation = (lineElement: string, palaceElement: string, lang: Language): string => {
  const mapToEn: Record<string, string> = {
    '金': 'Metal', '木': 'Wood', '水': 'Water', '火': 'Fire', '土': 'Earth',
    'Metal': 'Metal', 'Wood': 'Wood', 'Water': 'Water', 'Fire': 'Fire', 'Earth': 'Earth'
  };

  const lEl = mapToEn[lineElement];
  const pEl = mapToEn[palaceElement];
  const relation = ELEMENT_RELATIONS[lEl][pEl];
  const t = UI_TEXT[lang];

  switch (relation) {
    case 'Same': return t.rel_brother;
    case 'GeneratedBy': return t.rel_parent;
    case 'Generate': return t.rel_offspring;
    case 'Overcome': return t.rel_wealth;
    case 'OvercomedBy': return t.rel_official;
    default: return '?';
  }
};

// Algorithm to find the Palace (Gong) and Shi/Ying positions
const findPalaceState = (lines: number[]) => {
    // lines: array of 0/1 (bottom to top)
    // Helper: is pure? (Upper == Lower)
    const isPure = (ls: number[]) => {
        const lower = (ls[2]<<2)|(ls[1]<<1)|ls[0];
        const upper = (ls[5]<<2)|(ls[4]<<1)|ls[3];
        return lower === upper;
    };

    let temp = [...lines];
    
    // 1. Pure?
    if (isPure(temp)) return { palaceLine: 6, shi: 5, ying: 2, variant: 'Pure' };

    // 2. Flip 1 (Bottom)
    temp[0] = temp[0] ^ 1;
    if (isPure(temp)) return { palaceLine: 1, shi: 0, ying: 3, variant: 'Gen 1' };

    // 3. Flip 2
    temp[1] = temp[1] ^ 1;
    if (isPure(temp)) return { palaceLine: 2, shi: 1, ying: 4, variant: 'Gen 2' };

    // 4. Flip 3
    temp[2] = temp[2] ^ 1;
    if (isPure(temp)) return { palaceLine: 3, shi: 2, ying: 5, variant: 'Gen 3' };

    // 5. Flip 4
    temp[3] = temp[3] ^ 1;
    if (isPure(temp)) return { palaceLine: 4, shi: 3, ying: 0, variant: 'Gen 4' };

    // 6. Flip 5
    temp[4] = temp[4] ^ 1;
    if (isPure(temp)) return { palaceLine: 5, shi: 4, ying: 1, variant: 'Gen 5' };

    // 7. Wandering Soul (Flip 4 back)
    temp[3] = temp[3] ^ 1;
    if (isPure(temp)) return { palaceLine: 4, shi: 3, ying: 0, variant: 'Wandering' };

    // 8. Return Soul (Gui Hun)
    return { palaceLine: 3, shi: 2, ying: 5, variant: 'Return' };
};

export const interpretHexagramLocal = async (
  hexagram: HexagramData,
  language: Language
): Promise<string> => {
  await new Promise(resolve => setTimeout(resolve, 800));

  const t = UI_TEXT[language];
  const originalStruct = getHexagramStructure(hexagram.lines);
  const originalHexID = (originalStruct.upper << 3) | originalStruct.lower;
  
  // Future Hexagram Calculation
  const futureBinary = hexagram.lines.map(l => {
     if (l.lineType === LineType.ShaoYin) return 0;
     if (l.lineType === LineType.ShaoYang) return 1;
     if (l.lineType === LineType.LaoYin) return 1; // Change to Yang
     if (l.lineType === LineType.LaoYang) return 0; // Change to Yin
     return 0;
  });
  const fLower = (futureBinary[2]<<2)|(futureBinary[1]<<1)|futureBinary[0];
  const fUpper = (futureBinary[5]<<2)|(futureBinary[4]<<1)|futureBinary[3];
  const futureHexID = (fUpper << 3) | fLower;

  const origName = HEXAGRAM_NAMES[originalHexID]?.[language] || "Unknown";
  const futureName = HEXAGRAM_NAMES[futureHexID]?.[language] || "Unknown";

  const upTri = TRIGRAMS[originalStruct.upper][language];
  const loTri = TRIGRAMS[originalStruct.lower][language];

  // --- 1. Find Palace & Elements ---
  const palaceState = findPalaceState(originalStruct.lines);
  let pTemp: number[] = [...originalStruct.lines];
  if (palaceState.variant === 'Gen 1') pTemp[0] ^= 1;
  else if (palaceState.variant === 'Gen 2') { pTemp[0]^=1; pTemp[1]^=1; }
  else if (palaceState.variant === 'Gen 3') { pTemp[0]^=1; pTemp[1]^=1; pTemp[2]^=1; }
  else if (palaceState.variant === 'Gen 4') { pTemp[0]^=1; pTemp[1]^=1; pTemp[2]^=1; pTemp[3]^=1; }
  else if (palaceState.variant === 'Gen 5') { pTemp[0]^=1; pTemp[1]^=1; pTemp[2]^=1; pTemp[3]^=1; pTemp[4]^=1; }
  else if (palaceState.variant === 'Wandering') { pTemp[0]^=1; pTemp[1]^=1; pTemp[2]^=1; pTemp[3]^=1; pTemp[4]^=1; pTemp[3]^=1; }
  else if (palaceState.variant === 'Return') { 
      const u = originalStruct.upper;
      pTemp = [(u&1), (u>>1)&1, (u>>2)&1, (u&1), (u>>1)&1, (u>>2)&1];
  }
  
  const palaceTrigramID = (pTemp[5]<<2)|(pTemp[4]<<1)|pTemp[3]; 
  const palaceElement = TRIGRAMS[palaceTrigramID][language].element;
  const palaceName = TRIGRAMS[palaceTrigramID][language].name;

  // --- 2. Identify Shi/Ying Relations ---
  const shiIndex = palaceState.shi;
  const yingIndex = palaceState.ying;
  
  const shiTriID = shiIndex < 3 ? originalStruct.lower : originalStruct.upper;
  const yingTriID = yingIndex < 3 ? originalStruct.lower : originalStruct.upper;
  
  const shiElement = TRIGRAMS[shiTriID][language].element;
  const yingElement = TRIGRAMS[yingTriID][language].element;

  const shiRelationStr = getSixRelation(shiElement, palaceElement, language);
  const yingRelationStr = getSixRelation(yingElement, palaceElement, language);
  
  const shiRelKey = getRelKey(shiRelationStr, language);
  const yingRelKey = getRelKey(yingRelationStr, language);

  const shiDetails = RELATION_DETAILS[shiRelKey][language];
  const yingDetails = RELATION_DETAILS[yingRelKey][language];

  // --- 3. Interaction Logic ---
  const mapToEn = (e:string) => (['金','木','水','火','土'].includes(e) ? { '金':'Metal','木':'Wood','水':'Water','火':'Fire','土':'Earth' }[e] : e) || e;
  const sE = mapToEn(shiElement);
  const yE = mapToEn(yingElement);
  const syRel = ELEMENT_RELATIONS[sE][yE];
  const interaction = INTERACTION_DETAILS[syRel][language];

  // --- GENERATING MARKDOWN CONTENT ---

  // Section 1: Visual Meaning (Layman)
  // Describe the hexagram based on Upper/Lower attributes
  const imageDesc = language === 'en' 
    ? `The hexagram is composed of **${upTri.name} (${upTri.nature})** above and **${loTri.name} (${loTri.nature})** below.\n\n` +
      `It implies an environment where **${upTri.attribute}** is on the outside/future, and **${loTri.attribute}** is on the inside/foundation.`
    : `此卦由上卦**${upTri.name}（${upTri.nature}）**与下卦**${loTri.name}（${loTri.nature}）**组成。\n\n` +
      `**【白话解盘】**：\n` +
      `外在环境表现为“**${upTri.attribute}**”，而内在基础或起因是“**${loTri.attribute}**”。\n` +
      `想象一下，${upTri.nature}在${loTri.nature}之上，这意味着事物发展的基本态势。`;

  // Section 2: Diagnosis (Principle)
  const diagnosisText = language === 'en'
    ? `
- **Palace (Context)**: ${palaceName} (${palaceElement})
- **Subject (You)**: Holds **${shiRelationStr}**.
  - *Meaning*: ${shiDetails.meaning}
  - *Principle*: Your element is ${shiElement}, Palace is ${palaceElement}. ${shiDetails.principle}
- **Object (Other)**: Holds **${yingRelationStr}**.
  - *Meaning*: ${yingDetails.meaning}
    `
    : `
**1. 宫位基调（大背景）**
所属宫位：**${palaceName}宫（五行属${palaceElement}）**。这是整个卦象的能量源头。

**2. 世爻（代表你自己）**
- **持世关系**：**${shiRelationStr}** [五行属${shiElement}]
- **通俗含义**：${shiDetails.meaning}
- **诊断原理**：你的五行是${shiElement}，宫位是${palaceElement}。**${shiDetails.principle}** 这决定了你在当前局势中的角色。

**3. 应爻（代表对方/环境/目标）**
- **持应关系**：**${yingRelationStr}** [五行属${yingElement}]
- **通俗含义**：${yingDetails.meaning}
    `;

  // Section 3: Contradiction (Interaction)
  const contradictionText = language === 'en'
    ? `**Relationship**: ${interaction.summary}.\n${interaction.detail}`
    : `**${interaction.summary}**\n\n` +
      `> **深度解析**：${interaction.detail}\n` +
      `> **原理**：世爻（${shiElement}）与应爻（${yingElement}）之间的五行作用。`;

  // Section 4: Future & Change
  const hasChange = originalHexID !== futureHexID;
  const futureText = hasChange 
    ? (language === 'en' ? `Situation changes to **${futureName}**.` : `卦象发生变化，最终演变为 **${futureName}**。\n这暗示事情会有转折，需要关注动爻（变爻）带来的变数。`)
    : (language === 'en' ? "No moving lines. Situation is stable." : "本卦无动爻，也就是“静卦”。\n这意味着局势相对稳定、持久，应该以静制动，不宜盲目大动干戈。");

  // Section 5: Advice
  let adviceStr = "";
  if (shiRelKey === 'Wealth') adviceStr = language==='en'?"Good for finance/control.":"利于求财、经营、感情发展（男测女），在这个局势中你拥有控制权。";
  else if (shiRelKey === 'Official') adviceStr = language==='en'?"Stressful but authority.":"利于求名、升职，但需注意压力过大或身体健康，或者是受到严厉的管束。";
  else if (shiRelKey === 'Parent') adviceStr = language==='en'?"Documents/Study/Help.":"利于合同文书、考试、寻求长辈或上级庇护。同时也代表需要操劳、付出辛勤汗水。";
  else if (shiRelKey === 'Offspring') adviceStr = language==='en'?"Joy/Release/Creativity.":"利于投资、娱乐、解忧、创作。也是“克官”之神，利于摆脱官非压力，不利求官。";
  else if (shiRelKey === 'Brother') adviceStr = language==='en'?"Competition/Spending.":"利于合作、交友、竞争。但往往伴随着破财，或事情受到阻滞，有人争夺。";

  return `
# ${t.result_title}：${origName}

${imageDesc}

### ${t.sec_diagnosis}
${diagnosisText}

### ${t.sec_contradiction}
${contradictionText}

### ${t.sec_future}
${futureText}

### ${t.sec_advice}
${adviceStr}
  `;
};